## For tedious data cleaning

In [113]:
from sklearn.decomposition import PCA
import numpy as np
import scipy.spatial as scisp
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.patches as mpatches

In [114]:
zip2vec = np.load("zip2vec.npy")
indices = np.load("indices.npy")
zipcodes = np.load("zipcodes.npy")

In [115]:
zip2idx = {z : i for z, i in zip(zipcodes, indices)}
idx2zip = {i : z for i, z in zip(indices, zipcodes)}

In [32]:
a = zip2vec / (np.sum(zip2vec, axis=1, keepdims= True) + 1e-4)

In [112]:
# np.save("temp_embedding", )
# label =

    city scale      City Name
          1000           Avon
          1000     Bloomfield
             1        Windsor
          1000        Bristol
             1        Bristol
           100     Burlington
            10    Broad Brook
           100         Canaan
          1000         Canton
             1  Canton Center
            10   Collinsville
            10    East Berlin
             1    East Canaan
           100    East Granby
             1  East Hartland
           100      Ellington
             1     Farmington
            10  Falls Village
          1000     Farmington
          1000    Glastonbury
           100         Granby
          1000         Berlin
            10      Lakeville
          1000     Manchester
          1000     Manchester
           100         Bolton
             1     Manchester
             1    New Britain
          1000    New Britain
            10    New Britain
..         ...            ...
             1          Pasco
           100    Benton City
             1        Beverly
             1      Bickleton
            10        Burbank
           100  College Place
            10        Connell
           100         Dayton
             1        Eltopia
          1000      Kennewick
           100      Kennewick
           100      Kennewick
            10           Lind
            10           Mesa
           100        Othello
           100        Pomeroy
             1       Prescott
           100        Mattawa
           100        Prosser
          1000       Richland
           100  West Richland
           100       Richland
             1      Roosevelt
           100     Royal City
             1        Touchet
            10      Waitsburg
          1000    Walla Walla
             1      Washtucna
             1         Asotin
          1000      Clarkston

[29112 rows x 2 columns]

In [33]:
df = pd.DataFrame(a)

In [34]:
df.index = ["" for i in range(len(df))]

In [35]:
df

,0,1,2,3,4,5,6,7,8,9,10,11
,0.082466,0.082466,0.074735,0.000000,0.041233,0.025771,0.041233,0.201011,0.121122,0.144315,0.144315,0.041233
,0.071421,0.104156,0.035711,0.130939,0.130939,0.083325,0.071421,0.071421,0.005952,0.011904,0.190457,0.092253
,0.000000,0.000000,0.000000,0.999900,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
,0.058682,0.101256,0.077092,0.081695,0.151884,0.048327,0.040272,0.070189,0.020711,0.049477,0.159938,0.140377
,0.000000,0.000000,0.111100,0.888800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
,0.000000,0.159984,0.000000,0.359964,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.319968,0.159984
,0.000000,0.000000,0.249975,0.499950,0.000000,0.000000,0.249975,0.000000,0.000000,0.000000,0.000000,0.000000
,0.106184,0.106184,0.008849,0.141579,0.247763,0.035395,0.000000,0.070789,0.070789,0.000000,0.070789,0.141579
,0.068729,0.053210,0.002217,0.077598,0.177366,0.044341,0.017737,0.266049,0.133024,0.066512,0.039907,0.053210
,0.000000,0.000000,0.000000,0.000000,0.999900,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
,0.000000,0.000000,0.000000,0.363600,0.454500,0.000000,0.000000,0.000000,0.181800,0.000000,0.000000,0.000000
,0.000000,0.222200,0.222200,0.222200,0.000000,0.000000,0.000000,0.000000,0.000000,0.111100,0.222200,0.000000
,0.000000,0.000000,0.000000,0.000000,0.333300,0.000000,0.000000,0.000000,0.000000,0.000000,0.666600,0.000000
,0.239976,0.000000,0.000000,0.159984,0.159984,0.000000,0.079992,0.000000,0.000000,0.000000,0.279972,0.079992
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
,0.193731,0.000000,0.000000,0.124988,0.274973,0.024998,0.024998,0.024998,0.000000,0.000000,0.206229,0.124988
,0.000000,0.249975,0.249975,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.499950,0.000000,0.000000
,0.000000,0.000000,0.000000,0.615323,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.076915,0.307662
,0.025216,0.105712,0.055281,0.032005,0.009698,0.023276,0.019397,0.491706,0.048492,0.050431,0.057220,0.081466
,0.060258,0.088503,0.107334,0.047076,0.090386,0.000000,0.056492,0.218434,0.047076,0.050842,0.143112,0.090386
,0.077914,0.129857,0.051943,0.051943,0.168814,0.000000,0.006493,0.051943,0.103886,0.012986,0.240236,0.103886
,0.126303,0.113147,0.021051,0.063152,0.226293,0.052626,0.000000,0.047364,0.042101,0.036838,0.134197,0.136828
,0.347791,0.043474,0.086948,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.173896,0.347791
,0.050213,0.110615,0.071317,0.040025,0.085872,0.041481,0.048030,0.229962,0.082233,0.079322,0.080778,0.080050
,0.145714,0.027635,0.055271,0.095468,0.120591,0.140689,0.047734,0.200985,0.060295,0.045222,0.030148,0.030148
,0.246129,0.030766,0.123065,0.123065,0.138448,0.000000,0.000000,0.000000,0.000000,0.000000,0.215363,0.123065
,0.000000,0.000000,0.000000,0.499950,0.000000,0.000000,0.000000,0.000000,0.499950,0.000000,0.000000,0.000000
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.999900,0.000000,0.000000,0.000000,0.000000
,0.057528,0.090402,0.010958,0.076705,0.279424,0.060268,0.035613,0.093141,0.000000,0.010958,0.161628,0.123275
,0.000000,0.333300,0.000000,0.000000,0.333300,0.000000,0.000000,0.000000,0.000000,0.000000,0.333300,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
,0.000000,0.000000,0.000000,0.000000,0.999900,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
,0.079992,0.079992,0.000000,0.000000,0.199980,0.000000,0.000000,0.000000,0.000000,0.000000,0.319968,0.319968
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
,0.000000,0.000000,0.000000,0.999900,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
,0.285686,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.714214
,0.156847,0.039212,0.000000,0.000000,0.156847,0.078424,0.078424,0.000000,0.156847,0.078424,0.176453,0.078424
,0.000000,0.090900,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.545400,0.363600
,0.089879,0.089879,0.000000,0.089879,0.022470,0.000000,0.000000,0.000000,0.011235,0.011235,0.101113,0.584211
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
,0.066262,0.068434,0.073322,0.027156,0.159680,0.049968,0.047795,0.215079,0.051054,0.071693,0.073866,0.095591
,0.059994,0.059994,0.106656,0.053328,0.026664,0.053328,0.079992,0.026664,0.000000,0.000000,0.159984,0.373296
,0.037033,0.000000,0.000000,0.074067,0.592533,0.000000,0.000000,0.000000,0.000000,0.000000,0.296267,0.000000
,0.249975,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.249975,0.499950
,0.159984,0.000000,0.000000,0.000000,0.639936,0.000000,0.000000,0.000000,0.000000,0.000000,0.199980,0.000000
,0.186510,0.000000,0.010362,0.082893,0.186510,0.041447,0.000000,0.000000,0.015542,0.005181,0.170967,0.300488
,0.078939,0.210505,0.000000,0.026313,0.052626,0.000000,0.000000,0.000000,0.000000,0.000000,0.210505,0.421011
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.999900,0.000000
,0.059696,0.000000,0.000000,0.000000,0.119391,0.029848,0.119391,0.000000,0.000000,0.000000,0.552184,0.119391
,0.136738,0.000000,0.008546,0.042731,0.307662,0.000000,0.000000,0.000000,0.034185,0.000000,0.299115,0.170923
,0.090616,0.067181,0.076555,0.026560,0.140611,0.087491,0.040621,0.065618,0.096865,0.054682,0.093741,0.159359
,0.000000,0.000000,0.035084,0.035084,0.140337,0.000000,0.000000,0.000000,0.000000,0.000000,0.508721,0.280674
,0.127647,0.184379,0.184379,0.028366,0.028366,0.056732,0.000000,0.000000,0.000000,0.092189,0.056732,0.241111
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.999900,0.000000
,0.081624,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020406,0.000000,0.000000,0.489747,0.408122
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.999900
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.999900,0.000000
,0.113949,0.071218,0.059823,0.058399,0.195137,0.056974,0.037033,0.055550,0.035609,0.055550,0.129617,0.131041
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.999900
,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.999900
,0.111543,0.111543,0.051788,0.059755,0.215118,0.127477,0.031869,0.007967,0.015935,0.035853,0.151379,0.079673

In [39]:
# new_df = '\t'.join(str(r) for r in df.to_records())
new_df = '\n'.join('\t'.join(str(r) for r in rec) for rec in df.to_records())

In [43]:
with open("temp_embedding.tsv", "w", encoding="utf-8") as file:
    file.write(new_df)

In [50]:
zipdf = pd.DataFrame(zipcodes)
zipdf.index=  ["" for i in range(len(indices))]

In [54]:
new_zipdf = '\n'.join(''.join(str(r) for r in rec) for rec in zipdf.to_records())

In [55]:
with open("temp_idx.tsv", "w", encoding="utf-8") as file:
    file.write(new_zipdf)

In [72]:
data = pd.read_csv("data2.csv", index_col = 0)

In [78]:
append0 = np.vectorize(lambda x : str(x) if len(str(x)) == 5 else "0" + str(x))
data["zip"] = append0(data["zip"])

In [81]:
# a = data.loc[:, ["zip", "city scale", "City Name"]]

In [87]:
temp = data[data["scale"] == "Total"]
temp = temp[temp["level"] == 1]

In [91]:
a  = temp.loc[:, ["zip", "city scale", "City Name"]]

In [93]:
dic = {"tiny" : 1, "small" : 10, "medium" : 100, "large" : 1000}
replace = np.vectorize(lambda x : dic[x])
a["city scale"] = replace(a["city scale"])

In [95]:
a = a.drop("zip", 1)

In [97]:
a.index = ["" for i in range(len(a))]

In [109]:
a

    city scale      City Name
          1000           Avon
          1000     Bloomfield
             1        Windsor
          1000        Bristol
             1        Bristol
           100     Burlington
            10    Broad Brook
           100         Canaan
          1000         Canton
             1  Canton Center
            10   Collinsville
            10    East Berlin
             1    East Canaan
           100    East Granby
             1  East Hartland
           100      Ellington
             1     Farmington
            10  Falls Village
          1000     Farmington
          1000    Glastonbury
           100         Granby
          1000         Berlin
            10      Lakeville
          1000     Manchester
          1000     Manchester
           100         Bolton
             1     Manchester
             1    New Britain
          1000    New Britain
            10    New Britain
..         ...            ...
             1          Pasco
           100    Benton City
             1        Beverly
             1      Bickleton
            10        Burbank
           100  College Place
            10        Connell
           100         Dayton
             1        Eltopia
          1000      Kennewick
           100      Kennewick
           100      Kennewick
            10           Lind
            10           Mesa
           100        Othello
           100        Pomeroy
             1       Prescott
           100        Mattawa
           100        Prosser
          1000       Richland
           100  West Richland
           100       Richland
             1      Roosevelt
           100     Royal City
             1        Touchet
            10      Waitsburg
          1000    Walla Walla
             1      Washtucna
             1         Asotin
          1000      Clarkston

[29112 rows x 2 columns]

In [110]:
new_df = '\n'.join('\t'.join(str(r) for r in rec) for rec in a.to_records())

In [111]:
with open("temp_label.tsv", "w", encoding="utf-8") as file:
    file.write(new_df)

In [1]:
# new_df

In [ ]:
import sklearn as aa