In [3]:
import pandas as pd
import numpy as np

from tqdm import tqdm
import warnings
warnings.filterwarnings("ignore")

In [118]:
org_data = pd.read_csv('data2.csv')

In [221]:
org_data = org_data.drop('Unnamed: 0', 1)

In [119]:
zip_info = pd.read_csv('our_data/uszips.csv')

In [124]:
def zip_to_fip(zip_num):
    return zip_info[zip_info['zip'] == zip_num]['county_fip'].tolist()[0]
def zip_to_county(zip_num):
    result = zip_info[zip_info['zip'] == zip_num]['county_name'].tolist()
    if (len(result)):
        return result[0]
    else:
        return "NA"
def zip_to_county_fip(zip_num):
    result = zip_info[zip_info['zip'] == zip_num]['county_fips'].tolist()
    if (len(result)):
        return result[0]
    else:
        return float('nan')
def zip_to_lat(zip_num):
    result = zip_info[zip_info['zip'] == zip_num]['lat'].tolist()
    if (len(result)):
        return result[0]
    else:
        return float('nan')
def zip_to_lng(zip_num):
    result = zip_info[zip_info['zip'] == zip_num]['lng'].tolist()
    if (len(result)):
        return result[0]
    else:
        return float('nan')

In [121]:
counties = np.vectorize(lambda x : zip_to_county(x))(org_data['zip'].unique())

In [122]:
zip_curr = [0]
zip_cnt = [-1]
def assign_county(zip_num):
    if (zip_curr[0] != zip_num):
        zip_cnt[0] += 1
        zip_curr[0] = zip_num
    return counties[zip_cnt[0]]

In [123]:
org_data['County Names'] = [assign_county(i) for i in org_data['zip']]

In [125]:
county_fips = np.vectorize(lambda x : zip_to_county_fip(x))(org_data['zip'].unique())

In [126]:
zip_curr = [0]
zip_cnt = [-1]
def assign_county_fip(zip_num):
    if (zip_curr[0] != zip_num):
        zip_cnt[0] += 1
        zip_curr[0] = zip_num
    return county_fips[zip_cnt[0]].astype('int')

In [127]:
org_data['County Fips'] = [assign_county_fip(i) for i in org_data['zip']]

In [133]:
county_lat = np.vectorize(lambda x : zip_to_lat(x))(org_data['zip'].unique())
zip_curr = [0]
zip_cnt = [-1]
def assign_city_lat(zip_num):
    if (zip_curr[0] != zip_num):
        zip_cnt[0] += 1
        zip_curr[0] = zip_num
    return county_lat[zip_cnt[0]].astype('float')
org_data['City Lat'] = [assign_city_lat(i) for i in org_data['zip']]

In [134]:
county_lng = np.vectorize(lambda x : zip_to_lng(x))(org_data['zip'].unique())
zip_curr = [0]
zip_cnt = [-1]
def assign_city_lng(zip_num):
    if (zip_curr[0] != zip_num):
        zip_cnt[0] += 1
        zip_curr[0] = zip_num
    return county_lng[zip_cnt[0]].astype('float')
org_data['City Lng'] = [assign_city_lng(i) for i in org_data['zip']]

In [136]:
org_data

,Unnamed: 0,zip,NAICS.id,NAICS.display-label,RCPSZFE.display-label,ESTAB,City Name,State,level,weight,scale,city scale,County Names,County Fips,City Lat,City Lng
0,0,6001,44-45,Retail trade,All establishments,81,Avon,CT,1,0,Total,large,Hartford,9003,41.79071,-72.85384
1,1,6001,44-45,Retail trade,Establishments operated entire year with sales...,4,Avon,CT,1,1,D,large,Hartford,9003,41.79071,-72.85384
2,2,6001,44-45,Retail trade,Establishments operated entire year with sales...,8,Avon,CT,1,2,C,large,Hartford,9003,41.79071,-72.85384
3,3,6001,44-45,Retail trade,Establishments operated entire year with sales...,20,Avon,CT,1,4,B,large,Hartford,9003,41.79071,-72.85384
4,4,6001,44-45,Retail trade,Establishments operated entire year with sales...,36,Avon,CT,1,8,A,large,Hartford,9003,41.79071,-72.85384
5,5,6001,441,Motor vehicle and parts dealers,All establishments,2,Avon,CT,2,0,Total,large,Hartford,9003,41.79071,-72.85384
6,6,6001,441,Motor vehicle and parts dealers,Establishments operated entire year with sales...,2,Avon,CT,2,8,A,large,Hartford,9003,41.79071,-72.85384
7,7,6001,4411,Automobile dealers,All establishments,1,Avon,CT,3,0,Total,large,Hartford,9003,41.79071,-72.85384
8,8,6001,4411,Automobile dealers,Establishments operated entire year with sales...,1,Avon,CT,3,8,A,large,Hartford,9003,41.79071,-72.85384
9,9,6001,44111,New car dealers,All establishments,1,Avon,CT,4,0,Total,large,Hartford,9003,41.79071,-72.85384
10,10,6001,44111,New car dealers,Establishments operated entire year with sales...,1,Avon,CT,4,8,A,large,Hartford,9003,41.79071,-72.85384
11,11,6001,4413,"Automotive parts, accessories, and tire stores",All establishments,1,Avon,CT,3,0,Total,large,Hartford,9003,41.79071,-72.85384
12,12,6001,4413,"Automotive parts, accessories, and tire stores",Establishments operated entire year with sales...,1,Avon,CT,3,8,A,large,Hartford,9003,41.79071,-72.85384
13,13,6001,44132,Tire dealers,All establishments,1,Avon,CT,4,0,Total,large,Hartford,9003,41.79071,-72.85384
14,14,6001,44132,Tire dealers,Establishments operated entire year with sales...,1,Avon,CT,4,8,A,large,Hartford,9003,41.79071,-72.85384
15,15,6001,442,Furniture and home furnishings stores,All establishments,10,Avon,CT,2,0,Total,large,Hartford,9003,41.79071,-72.85384
16,16,6001,442,Furniture and home furnishings stores,Establishments operated entire year with sales...,1,Avon,CT,2,1,D,large,Hartford,9003,41.79071,-72.85384
17,17,6001,442,Furniture and home furnishings stores,Establishments operated entire year with sales...,1,Avon,CT,2,2,C,large,Hartford,9003,41.79071,-72.85384
18,18,6001,442,Furniture and home furnishings stores,Establishments operated entire year with sales...,3,Avon,CT,2,4,B,large,Hartford,9003,41.79071,-72.85384
19,19,6001,442,Furniture and home furnishings stores,Establishments operated entire year with sales...,4,Avon,CT,2,8,A,large,Hartford,9003,41.79071,-72.85384
20,20,6001,4421,Furniture stores,All establishments,2,Avon,CT,3,0,Total,large,Hartford,9003,41.79071,-72.85384
21,21,6001,4421,Furniture stores,Establishments operated entire year with sales...,1,Avon,CT,3,4,B,large,Hartford,9003,41.79071,-72.85384
22,22,6001,4421,Furniture stores,Establishments operated entire year with sales...,1,Avon,CT,3,8,A,large,Hartford,9003,41.79071,-72.85384
23,23,6001,4422,Home furnishings stores,All establishments,8,Avon,CT,3,0,Total,large,Hartford,9003,41.79071,-72.85384
24,24,6001,4422,Home furnishings stores,Establishments operated entire year with sales...,1,Avon,CT,3,1,D,large,Hartford,9003,41.79071,-72.85384
25,25,6001,4422,Home furnishings stores,Establishments operated entire year with sales...,1,Avon,CT,3,2,C,large,Hartford,9003,41.79071,-72.85384
26,26,6001,4422,Home furnishings stores,Establishments operated entire year with sales...,2,Avon,CT,3,4,B,large,Hartford,9003,41.79071,-72.85384
27,27,6001,4422,Home furnishings stores,Establishments operated entire year with sales...,3,Avon,CT,3,8,A,large,Hartford,9003,41.79071,-72.85384
28,28,6001,44221,Floor covering stores,All establishments,2,Avon,CT,4,0,Total,large,Hartford,9003,41.79071,-72.85384
29,29,6001,44221,Floor covering stores,Establishments operated entire year with sales...,2,Avon,CT,4,4,B,large,Hartford,9003,41.79071,-72.85384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2211924,2211924,99403,453,Miscellaneous store retailers,Establishments operated entire year with sales...,1,Clarkston,WA,2,1,D,large,Asotin,53003,46.37243,-117.25274
2211925,2211925,99403,453,Miscellaneous store retailers,Establishments operated entire year with sales...,2,Clarkston,WA,2,2,C,large,Asotin,53003,46.37243,-117.25274
2211926,2211926,99403,453,Miscellaneous store retailers,Establishments operated entire year with sales...,1,Clarkston,WA,2,8,A,large,Asotin,53003,46.37243,-117.25274
2211927,2211927,99403,4533,Used merchandise stores,All establishments,2,Clarkston,WA,3,0,Total,large,Asotin,53003,46.37243,-117.25274
2211928,2211928,99403,4533,Used merchandise stores,Establishments operated entire year with sales...,1,Clarkston,WA,3,1,D,large,Asotin,53003,46.37243,-117.25274
2211929,2211929,99403,4533,Used merchandise stores,Establishments operated entire year with sales...,1,Clarkston,WA,3,2,C,large,Asotin,53003,46.37243,-117.25274
2211930,2211930,99403,4539,Other miscellaneous store retailers,All establishments,2,Clarkston,WA,3,0,Total,large,Asotin,53003,46.37243,-117.25274
2211931,2211931,99403,4539,Other miscellaneous store retailers,Establishments operated entire year with sales...,1,Clarkston,WA,3,2,C,large,Asotin,53003,46.37243,-117.25274
2211932,2211932,99403,4539,Other miscellaneous store retailers,Establishments operated entire year with sales...,1,Clarkston,WA,3,8,A,large,Asotin,53003,46.37243,-117.25274
2211933,2211933,99403,45393,Manufactured (mobile) home dealers,All establishments,1,Clarkston,WA,4,0,Total,large,Asotin,53003,46.37243,-117.25274
2211934,2211934,99403,45393,Manufactured (mobile) home dealers,Establishments operated entire year with sales...,1,Clarkston,WA,4,8,A,large,Asotin,53003,46.37243,-117.25274
2211935,2211935,99403,45399,All other miscellaneous store retailers,All establishments,1,Clarkston,WA,4,0,Total,large,Asotin,53003,46.37243,-117.25274
2211936,2211936,99403,45399,All other miscellaneous store retailers,Establishments operated entire year with sales...,1,Clarkston,WA,4,2,C,large,Asotin,53003,46.37243,-117.25274
2211937,2211937,99403,453998,All other miscellaneous store retailers (excep...,All establishments,1,Clarkston,WA,5,0,Total,large,Asotin,53003,46.37243,-117.25274
2211938,2211938,99403,453998,All other miscellaneous store retailers (excep...,Establishments operated entire year with sales...,1,Clarkston,WA,5,2,C,large,Asotin,53003,46.37243,-117.25274
2211939,2211939,99403,454,Nonstore retailers,All establishments,7,Clarkston,WA,2,0,Total,large,Asotin,53003,46.37243,-117.25274
2211940,2211940,99403,454,Nonstore retailers,Establishments operated entire year with sales...,3,Clarkston,WA,2,1,D,large,Asotin,53003,46.37243,-117.25274
2211941,2211941,99403,454,Nonstore retailers,Establishments operated entire year with sales...,1,Clarkston,WA,2,4,B,large,Asotin,53003,46.37243,-117.25274
2211942,2211942,99403,454,Nonstore retailers,Establishments operated entire year with sales...,1,Clarkston,WA,2,8,A,large,Asotin,53003,46.37243,-117.25274
2211943,2211943,99403,4541,Electronic shopping and mail-order houses,All establishments,2,Clarkston,WA,3,0,Total,large,Asotin,53003,46.37243,-117.25274
2211944,2211944,99403,454111,Electronic shopping,All establishments,2,Clarkston,WA,5,0,Total,large,Asotin,53003,46.37243,-117.25274
2211945,2211945,99403,4543,Direct selling establishments,All establishments,5,Clarkston,WA,3,0,Total,large,Asotin,53003,46.37243,-117.25274
2211946,2211946,99403,4543,Direct selling establishments,Establishments operated entire year with sales...,3,Clarkston,WA,3,1,D,large,Asotin,53003,46.37243,-117.25274
2211947,2211947,99403,4543,Direct selling establishments,Establishments operated entire year with sales...,1,Clarkston,WA,3,4,B,large,Asotin,53003,46.37243,-117.25274
2211948,2211948,99403,4543,Direct selling establishments,Establishments operated entire year with sales...,1,Clarkston,WA,3,8,A,large,Asotin,53003,46.37243,-117.25274
2211949,2211949,99403,45431,Fuel dealers,All establishments,1,Clarkston,WA,4,0,Total,large,Asotin,53003,46.37243,-117.25274
2211950,2211950,99403,45431,Fuel dealers,Establishments operated entire year with sales...,1,Clarkston,WA,4,4,B,large,Asotin,53003,46.37243,-117.25274
2211951,2211951,99403,45439,Other direct selling establishments,All establishments,4,Clarkston,WA,4,0,Total,large,Asotin,53003,46.37243,-117.25274
2211952,2211952,99403,45439,Other direct selling establishments,Establishments operated entire year with sales...,3,Clarkston,WA,4,1,D,large,Asotin,53003,46.37243,-117.25274
2211953,2211953,99403,45439,Other direct selling establishments,Establishments operated entire year with sales...,1,Clarkston,WA,4,8,A,large,Asotin,53003,46.37243,-117.25274

In [137]:
org_data.to_csv('data2_with_county.csv')

In [105]:
gdp_data = pd.read_csv('our_data/gdp_by_county_fips.csv', encoding='ISO-8859–1')

In [106]:
# drop GDP data of years other than 2012
for i in range(2013, 2019):
    gdp_data = gdp_data.drop(str(i), 1)
for i in range(2001, 2012):
    gdp_data = gdp_data.drop(str(i), 1)

In [107]:
# drop data for US as a whole
gdp_data = gdp_data[gdp_data['GeoName'] != 'United States']

In [108]:
# drop NaN data
gdp_data = gdp_data.dropna()

In [109]:
gdp_data

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,2012
34,"""01000""",Alabama,5,CAGDP9,1.0,...,All industry total,Thousands of chained 2012 dollars,186298987
35,"""01000""",Alabama,5,CAGDP9,2.0,...,Private industries,Thousands of chained 2012 dollars,154280965
36,"""01000""",Alabama,5,CAGDP9,3.0,11,"Agriculture, forestry, fishing and hunting",Thousands of chained 2012 dollars,1802169
37,"""01000""",Alabama,5,CAGDP9,6.0,21,"Mining, quarrying, and oil and gas extraction",Thousands of chained 2012 dollars,2891824
38,"""01000""",Alabama,5,CAGDP9,10.0,22,Utilities,Thousands of chained 2012 dollars,5689355
39,"""01000""",Alabama,5,CAGDP9,11.0,23,Construction,Thousands of chained 2012 dollars,6878611
40,"""01000""",Alabama,5,CAGDP9,12.0,31-33,Manufacturing,Thousands of chained 2012 dollars,31921808
41,"""01000""",Alabama,5,CAGDP9,13.0,"321,327-339",Durable goods manufacturing,Thousands of chained 2012 dollars,19242776
42,"""01000""",Alabama,5,CAGDP9,25.0,"311-316,322-326",Nondurable goods manufacturing,Thousands of chained 2012 dollars,12679031
43,"""01000""",Alabama,5,CAGDP9,34.0,42,Wholesale trade,Thousands of chained 2012 dollars,10603959
44,"""01000""",Alabama,5,CAGDP9,35.0,44-45,Retail trade,Thousands of chained 2012 dollars,12550419
45,"""01000""",Alabama,5,CAGDP9,36.0,48-49,Transportation and warehousing,Thousands of chained 2012 dollars,4802396
46,"""01000""",Alabama,5,CAGDP9,45.0,51,Information,Thousands of chained 2012 dollars,4252373
47,"""01000""",Alabama,5,CAGDP9,50.0,"52, 53","Finance, insurance, real estate, rental, and...",Thousands of chained 2012 dollars,30379075
48,"""01000""",Alabama,5,CAGDP9,51.0,52,Finance and insurance,Thousands of chained 2012 dollars,10219744
49,"""01000""",Alabama,5,CAGDP9,56.0,53,Real estate and rental and leasing,Thousands of chained 2012 dollars,20159331
50,"""01000""",Alabama,5,CAGDP9,59.0,"54, 55, 56",Professional and business services,Thousands of chained 2012 dollars,17744080
51,"""01000""",Alabama,5,CAGDP9,60.0,54,"Professional, scientific, and technical ser...",Thousands of chained 2012 dollars,11082521
52,"""01000""",Alabama,5,CAGDP9,64.0,55,Management of companies and enterprises,Thousands of chained 2012 dollars,1859552
53,"""01000""",Alabama,5,CAGDP9,65.0,56,Administrative and support and waste manage...,Thousands of chained 2012 dollars,4802007
54,"""01000""",Alabama,5,CAGDP9,68.0,"61, 62","Educational services, health care, and socia...",Thousands of chained 2012 dollars,14587260
55,"""01000""",Alabama,5,CAGDP9,69.0,61,Educational services,Thousands of chained 2012 dollars,1197515
56,"""01000""",Alabama,5,CAGDP9,70.0,62,Health care and social assistance,Thousands of chained 2012 dollars,13389746
57,"""01000""",Alabama,5,CAGDP9,75.0,"71, 72","Arts, entertainment, recreation, accommodati...",Thousands of chained 2012 dollars,5347583
58,"""01000""",Alabama,5,CAGDP9,76.0,71,"Arts, entertainment, and recreation",Thousands of chained 2012 dollars,670767
59,"""01000""",Alabama,5,CAGDP9,79.0,72,Accommodation and food services,Thousands of chained 2012 dollars,4676815
60,"""01000""",Alabama,5,CAGDP9,82.0,81,Other services (except government and govern...,Thousands of chained 2012 dollars,4830053
61,"""01000""",Alabama,5,CAGDP9,83.0,...,Government and government enterprises,Thousands of chained 2012 dollars,32018022
62,"""01000""",Alabama,5,CAGDP9,87.0,"11, 21",Natural resources and mining,Thousands of chained 2012 dollars,4693993
63,"""01000""",Alabama,5,CAGDP9,88.0,"42, 44-45",Trade,Thousands of chained 2012 dollars,23154378
...,...,...,...,...,...,...,...,...,...
107954,"""98000""",Far West,8,CAGDP9,10.0,22,Utilities,Thousands of chained 2012 dollars,41510400
107955,"""98000""",Far West,8,CAGDP9,11.0,23,Construction,Thousands of chained 2012 dollars,93460690
107956,"""98000""",Far West,8,CAGDP9,12.0,31-33,Manufacturing,Thousands of chained 2012 dollars,329621061
107957,"""98000""",Far West,8,CAGDP9,13.0,"321,327-339",Durable goods manufacturing,Thousands of chained 2012 dollars,215514401
107958,"""98000""",Far West,8,CAGDP9,25.0,"311-316,322-326",Nondurable goods manufacturing,Thousands of chained 2012 dollars,114106660
107959,"""98000""",Far West,8,CAGDP9,34.0,42,Wholesale trade,Thousands of chained 2012 dollars,164089182
107960,"""98000""",Far West,8,CAGDP9,35.0,44-45,Retail trade,Thousands of chained 2012 dollars,173232279
107961,"""98000""",Far West,8,CAGDP9,36.0,48-49,Transportation and warehousing,Thousands of chained 2012 dollars,78983332
107962,"""98000""",Far West,8,CAGDP9,45.0,51,Information,Thousands of chained 2012 dollars,205869987
107963,"""98000""",Far West,8,CAGDP9,50.0,"52, 53","Finance, insurance, real estate, rental, and...",Thousands of chained 2012 dollars,609932512
107964,"""98000""",Far West,8,CAGDP9,51.0,52,Finance and insurance,Thousands of chained 2012 dollars,144856162
107965,"""98000""",Far West,8,CAGDP9,56.0,53,Real estate and rental and leasing,Thousands of chained 2012 dollars,465076351
107966,"""98000""",Far West,8,CAGDP9,59.0,"54, 55, 56",Professional and business services,Thousands of chained 2012 dollars,378405644
107967,"""98000""",Far West,8,CAGDP9,60.0,54,"Professional, scientific, and technical ser...",Thousands of chained 2012 dollars,247732632
107968,"""98000""",Far West,8,CAGDP9,64.0,55,Management of companies and enterprises,Thousands of chained 2012 dollars,43332588
107969,"""98000""",Far West,8,CAGDP9,65.0,56,Administrative and support and waste manage...,Thousands of chained 2012 dollars,87340423
107970,"""98000""",Far West,8,CAGDP9,68.0,"61, 62","Educational services, health care, and socia...",Thousands of chained 2012 dollars,224984408
107971,"""98000""",Far West,8,CAGDP9,69.0,61,Educational services,Thousands of chained 2012 dollars,32034857
107972,"""98000""",Far West,8,CAGDP9,70.0,62,Health care and social assistance,Thousands of chained 2012 dollars,192949551
107973,"""98000""",Far West,8,CAGDP9,75.0,"71, 72","Arts, entertainment, recreation, accommodati...",Thousands of chained 2012 dollars,138730717
107974,"""98000""",Far West,8,CAGDP9,76.0,71,"Arts, entertainment, and recreation",Thousands of chained 2012 dollars,43418411
107975,"""98000""",Far West,8,CAGDP9,79.0,72,Accommodation and food services,Thousands of chained 2012 dollars,95312306
107976,"""98000""",Far West,8,CAGDP9,82.0,81,Other services (except government and govern...,Thousands of chained 2012 dollars,60680184
107977,"""98000""",Far West,8,CAGDP9,83.0,...,Government and government enterprises,Thousands of chained 2012 dollars,387046875
107978,"""98000""",Far West,8,CAGDP9,87.0,"11, 21",Natural resources and mining,Thousands of chained 2012 dollars,92602220
107979,"""98000""",Far West,8,CAGDP9,88.0,"42, 44-45",Trade,Thousands of chained 2012 dollars,337321461
107980,"""98000""",Far West,8,CAGDP9,89.0,...,Transportation and utilities,Thousands of chained 2012 dollars,120493733
107981,"""98000""",Far West,8,CAGDP9,90.0,...,Manufacturing and information,Thousands of chained 2012 dollars,(NA)
107982,"""98000""",Far West,8,CAGDP9,91.0,...,Private goods-producing industries 2/,Thousands of chained 2012 dollars,515683970
107983,"""98000""",Far West,8,CAGDP9,92.0,...,Private services-providing industries 3/,Thousands of chained 2012 dollars,2076418646

In [110]:
# drop useless columns
gdp_data = gdp_data.drop('Region', 1)
gdp_data = gdp_data.drop('TableName', 1)

In [115]:
gdp_data['GeoFIPS'] = np.vectorize(lambda x : x[1:-1])(gdp_data['GeoFIPS'])

In [116]:
gdp_data

,GeoFIPS,GeoName,LineCode,IndustryClassification,Description,Unit,2012
34,01000,Alabama,1.0,...,All industry total,Thousands of chained 2012 dollars,186298987
35,01000,Alabama,2.0,...,Private industries,Thousands of chained 2012 dollars,154280965
36,01000,Alabama,3.0,11,"Agriculture, forestry, fishing and hunting",Thousands of chained 2012 dollars,1802169
37,01000,Alabama,6.0,21,"Mining, quarrying, and oil and gas extraction",Thousands of chained 2012 dollars,2891824
38,01000,Alabama,10.0,22,Utilities,Thousands of chained 2012 dollars,5689355
39,01000,Alabama,11.0,23,Construction,Thousands of chained 2012 dollars,6878611
40,01000,Alabama,12.0,31-33,Manufacturing,Thousands of chained 2012 dollars,31921808
41,01000,Alabama,13.0,"321,327-339",Durable goods manufacturing,Thousands of chained 2012 dollars,19242776
42,01000,Alabama,25.0,"311-316,322-326",Nondurable goods manufacturing,Thousands of chained 2012 dollars,12679031
43,01000,Alabama,34.0,42,Wholesale trade,Thousands of chained 2012 dollars,10603959
44,01000,Alabama,35.0,44-45,Retail trade,Thousands of chained 2012 dollars,12550419
45,01000,Alabama,36.0,48-49,Transportation and warehousing,Thousands of chained 2012 dollars,4802396
46,01000,Alabama,45.0,51,Information,Thousands of chained 2012 dollars,4252373
47,01000,Alabama,50.0,"52, 53","Finance, insurance, real estate, rental, and...",Thousands of chained 2012 dollars,30379075
48,01000,Alabama,51.0,52,Finance and insurance,Thousands of chained 2012 dollars,10219744
49,01000,Alabama,56.0,53,Real estate and rental and leasing,Thousands of chained 2012 dollars,20159331
50,01000,Alabama,59.0,"54, 55, 56",Professional and business services,Thousands of chained 2012 dollars,17744080
51,01000,Alabama,60.0,54,"Professional, scientific, and technical ser...",Thousands of chained 2012 dollars,11082521
52,01000,Alabama,64.0,55,Management of companies and enterprises,Thousands of chained 2012 dollars,1859552
53,01000,Alabama,65.0,56,Administrative and support and waste manage...,Thousands of chained 2012 dollars,4802007
54,01000,Alabama,68.0,"61, 62","Educational services, health care, and socia...",Thousands of chained 2012 dollars,14587260
55,01000,Alabama,69.0,61,Educational services,Thousands of chained 2012 dollars,1197515
56,01000,Alabama,70.0,62,Health care and social assistance,Thousands of chained 2012 dollars,13389746
57,01000,Alabama,75.0,"71, 72","Arts, entertainment, recreation, accommodati...",Thousands of chained 2012 dollars,5347583
58,01000,Alabama,76.0,71,"Arts, entertainment, and recreation",Thousands of chained 2012 dollars,670767
59,01000,Alabama,79.0,72,Accommodation and food services,Thousands of chained 2012 dollars,4676815
60,01000,Alabama,82.0,81,Other services (except government and govern...,Thousands of chained 2012 dollars,4830053
61,01000,Alabama,83.0,...,Government and government enterprises,Thousands of chained 2012 dollars,32018022
62,01000,Alabama,87.0,"11, 21",Natural resources and mining,Thousands of chained 2012 dollars,4693993
63,01000,Alabama,88.0,"42, 44-45",Trade,Thousands of chained 2012 dollars,23154378
...,...,...,...,...,...,...,...
107954,98000,Far West,10.0,22,Utilities,Thousands of chained 2012 dollars,41510400
107955,98000,Far West,11.0,23,Construction,Thousands of chained 2012 dollars,93460690
107956,98000,Far West,12.0,31-33,Manufacturing,Thousands of chained 2012 dollars,329621061
107957,98000,Far West,13.0,"321,327-339",Durable goods manufacturing,Thousands of chained 2012 dollars,215514401
107958,98000,Far West,25.0,"311-316,322-326",Nondurable goods manufacturing,Thousands of chained 2012 dollars,114106660
107959,98000,Far West,34.0,42,Wholesale trade,Thousands of chained 2012 dollars,164089182
107960,98000,Far West,35.0,44-45,Retail trade,Thousands of chained 2012 dollars,173232279
107961,98000,Far West,36.0,48-49,Transportation and warehousing,Thousands of chained 2012 dollars,78983332
107962,98000,Far West,45.0,51,Information,Thousands of chained 2012 dollars,205869987
107963,98000,Far West,50.0,"52, 53","Finance, insurance, real estate, rental, and...",Thousands of chained 2012 dollars,609932512
107964,98000,Far West,51.0,52,Finance and insurance,Thousands of chained 2012 dollars,144856162
107965,98000,Far West,56.0,53,Real estate and rental and leasing,Thousands of chained 2012 dollars,465076351
107966,98000,Far West,59.0,"54, 55, 56",Professional and business services,Thousands of chained 2012 dollars,378405644
107967,98000,Far West,60.0,54,"Professional, scientific, and technical ser...",Thousands of chained 2012 dollars,247732632
107968,98000,Far West,64.0,55,Management of companies and enterprises,Thousands of chained 2012 dollars,43332588
107969,98000,Far West,65.0,56,Administrative and support and waste manage...,Thousands of chained 2012 dollars,87340423
107970,98000,Far West,68.0,"61, 62","Educational services, health care, and socia...",Thousands of chained 2012 dollars,224984408
107971,98000,Far West,69.0,61,Educational services,Thousands of chained 2012 dollars,32034857
107972,98000,Far West,70.0,62,Health care and social assistance,Thousands of chained 2012 dollars,192949551
107973,98000,Far West,75.0,"71, 72","Arts, entertainment, recreation, accommodati...",Thousands of chained 2012 dollars,138730717
107974,98000,Far West,76.0,71,"Arts, entertainment, and recreation",Thousands of chained 2012 dollars,43418411
107975,98000,Far West,79.0,72,Accommodation and food services,Thousands of chained 2012 dollars,95312306
107976,98000,Far West,82.0,81,Other services (except government and govern...,Thousands of chained 2012 dollars,60680184
107977,98000,Far West,83.0,...,Government and government enterprises,Thousands of chained 2012 dollars,387046875
107978,98000,Far West,87.0,"11, 21",Natural resources and mining,Thousands of chained 2012 dollars,92602220
107979,98000,Far West,88.0,"42, 44-45",Trade,Thousands of chained 2012 dollars,337321461
107980,98000,Far West,89.0,...,Transportation and utilities,Thousands of chained 2012 dollars,120493733
107981,98000,Far West,90.0,...,Manufacturing and information,Thousands of chained 2012 dollars,(NA)
107982,98000,Far West,91.0,...,Private goods-producing industries 2/,Thousands of chained 2012 dollars,515683970
107983,98000,Far West,92.0,...,Private services-providing industries 3/,Thousands of chained 2012 dollars,2076418646

In [95]:
gdp_data.iloc[0:107990:34]['2012']

34         186298987
68           1482770
102          5016735
136           726909
170           374435
204           804763
238           253214
272           565044
306          4260733
340           752850
374           486349
408           820985
442           568763
476           800455
510           282082
544           270776
578          1198684
612          2423750
646           513044
680           157905
714          1105577
748           414188
782          2298846
816          2689377
850          1254605
884          1589171
918          1559648
952          1250140
986          2801621
1020          456379
             ...
106964        504155
106998       7114574
107032       1365092
107066       1171734
107100        284411
107134       1724578
107168        494289
107202        233883
107236        541791
107270       5076898
107304        689737
107338       5304065
107372        103846
107406       1370964
107440        537454
107474       1235608
107508       1686613
107542       4125786
107576       1797679
107610       1000364
107644        370014
107678        322557
107712     889223258
107746    2993044930
107780    2252275720
107814    1057845446
107848    3431042083
107882    1940752835
107916     540442367
107950    2979149491
Name: 2012, Length: 3175, dtype: object

In [104]:
lines = [2,3,6,10,11,12,13,25,34,35,36,45,50,51,56,59,60,64,65,68,69,70,75,76,79,82,83,87,88,89,90,91,92]
def clean_total(total_gdp):
    if (total_gdp == '(NA)'):
        return float(100)
    elif (total_gdp == '(D)'):
        return float(1)
    else:
        return float(total_gdp)
def percentage_gdp(input_num, total_gdp):
    if (input_num == '(NA)'):
        return float('nan')
    elif (input_num == '(D)'):
        return float(0)
    else:
        return (float(input_num) / total_gdp)
cnt = 0
gdp_data.iloc[0:107990:34]['2012'] = np.vectorize(lambda x : clean_total(x))(gdp_data.iloc[0:107990:34]['2012'])
gdp_data.iloc[1:107990:34]['2012'] = np.vectorize(lambda x,y : percentage_gdp(x,float(y)))(gdp_data.iloc[1:107990:34]['2012'], gdp_data.iloc[0:107990:34]['2012'])

ValueError: could not convert string to float: '(NA)'

In [91]:
all_result

,GeoFIPS,GeoName,LineCode,IndustryClassification,Description,Unit,2012
34,"""01000""",Alabama,1.0,...,All industry total,Thousands of chained 2012 dollars,186298987
68,"""01001""","Autauga, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,1482770
102,"""01003""","Baldwin, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,5016735
136,"""01005""","Barbour, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,726909
170,"""01007""","Bibb, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,374435
204,"""01009""","Blount, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,804763
238,"""01011""","Bullock, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,253214
272,"""01013""","Butler, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,565044
306,"""01015""","Calhoun, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,4260733
340,"""01017""","Chambers, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,752850
374,"""01019""","Cherokee, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,486349
408,"""01021""","Chilton, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,820985
442,"""01023""","Choctaw, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,568763
476,"""01025""","Clarke, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,800455
510,"""01027""","Clay, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,282082
544,"""01029""","Cleburne, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,270776
578,"""01031""","Coffee, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,1198684
612,"""01033""","Colbert, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,2423750
646,"""01035""","Conecuh, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,513044
680,"""01037""","Coosa, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,157905
714,"""01039""","Covington, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,1105577
748,"""01041""","Crenshaw, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,414188
782,"""01043""","Cullman, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,2298846
816,"""01045""","Dale, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,2689377
850,"""01047""","Dallas, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,1254605
884,"""01049""","DeKalb, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,1589171
918,"""01051""","Elmore, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,1559648
952,"""01053""","Escambia, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,1250140
986,"""01055""","Etowah, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,2801621
1020,"""01057""","Fayette, AL",1.0,...,All industry total,Thousands of chained 2012 dollars,456379
...,...,...,...,...,...,...,...
106964,"""56003""","Big Horn, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,504155
106998,"""56005""","Campbell, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,7114574
107032,"""56007""","Carbon, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,1365092
107066,"""56009""","Converse, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,1171734
107100,"""56011""","Crook, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,284411
107134,"""56013""","Fremont, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,1724578
107168,"""56015""","Goshen, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,494289
107202,"""56017""","Hot Springs, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,233883
107236,"""56019""","Johnson, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,541791
107270,"""56021""","Laramie, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,5076898
107304,"""56023""","Lincoln, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,689737
107338,"""56025""","Natrona, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,5304065
107372,"""56027""","Niobrara, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,103846
107406,"""56029""","Park, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,1370964
107440,"""56031""","Platte, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,537454
107474,"""56033""","Sheridan, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,1235608
107508,"""56035""","Sublette, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,1686613
107542,"""56037""","Sweetwater, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,4125786
107576,"""56039""","Teton, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,1797679
107610,"""56041""","Uinta, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,1000364
107644,"""56043""","Washakie, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,370014
107678,"""56045""","Weston, WY",1.0,...,All industry total,Thousands of chained 2012 dollars,322557
107712,"""91000""",New England,1.0,...,All industry total,Thousands of chained 2012 dollars,889223258
107746,"""92000""",Mideast,1.0,...,All industry total,Thousands of chained 2012 dollars,2993044930
107780,"""93000""",Great Lakes,1.0,...,All industry total,Thousands of chained 2012 dollars,2252275720
107814,"""94000""",Plains,1.0,...,All industry total,Thousands of chained 2012 dollars,1057845446
107848,"""95000""",Southeast,1.0,...,All industry total,Thousands of chained 2012 dollars,3431042083
107882,"""96000""",Southwest,1.0,...,All industry total,Thousands of chained 2012 dollars,1940752835
107916,"""97000""",Rocky Mountain,1.0,...,All industry total,Thousands of chained 2012 dollars,540442367
107950,"""98000""",Far West,1.0,...,All industry total,Thousands of chained 2012 dollars,2979149491

In [117]:
gdp_data.to_csv('county_to_gdp_by_industry_data.csv')

In [61]:
pop_data = pd.read_csv('our_data/cc-est2012-alldata.csv', encoding='ISO-8859–1')

In [62]:
# drop unneed columns
pop_data = pop_data.drop('SUMLEV', 1)
pop_data = pop_data[pop_data['YEAR'] == 5] # only leave 2012 data in table
pop_data = pop_data.drop('YEAR', 1)

In [63]:
pop_data

,STATE,COUNTY,STNAME,CTYNAME,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,WA_MALE,WA_FEMALE,...,HWAC_MALE,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE
76,1,1,Alabama,Autauga County,0,55514,27053,28461,21383,22185,...,652,585,68,57,39,44,15,11,21,9
77,1,1,Alabama,Autauga County,1,3609,1877,1732,1391,1308,...,90,80,7,6,6,1,2,2,0,0
78,1,1,Alabama,Autauga County,2,3819,1922,1897,1468,1447,...,68,72,5,6,7,7,2,2,2,0
79,1,1,Alabama,Autauga County,3,4402,2221,2181,1684,1678,...,67,58,7,4,7,8,1,0,4,1
80,1,1,Alabama,Autauga County,4,4116,2149,1967,1565,1466,...,48,41,8,5,4,6,5,1,2,0
81,1,1,Alabama,Autauga County,5,3423,1753,1670,1288,1247,...,51,32,5,6,1,1,1,0,3,1
82,1,1,Alabama,Autauga County,6,3209,1577,1632,1225,1255,...,55,56,7,6,2,4,2,2,5,3
83,1,1,Alabama,Autauga County,7,3337,1603,1734,1265,1290,...,57,45,11,5,0,4,0,0,1,0
84,1,1,Alabama,Autauga County,8,3863,1845,2018,1449,1496,...,52,43,2,2,4,5,1,0,3,1
85,1,1,Alabama,Autauga County,9,4178,2013,2165,1646,1681,...,48,35,4,2,3,3,0,1,0,2
86,1,1,Alabama,Autauga County,10,4096,2005,2091,1633,1668,...,27,38,2,6,3,1,0,1,1,0
87,1,1,Alabama,Autauga County,11,4133,2071,2062,1697,1632,...,29,17,4,5,1,1,1,0,0,0
88,1,1,Alabama,Autauga County,12,3271,1557,1714,1236,1350,...,18,19,3,0,1,0,0,1,0,0
89,1,1,Alabama,Autauga County,13,2814,1342,1472,1132,1165,...,13,12,0,1,0,2,0,0,0,1
90,1,1,Alabama,Autauga County,14,2494,1099,1395,939,1175,...,9,9,1,2,0,0,0,1,0,0
91,1,1,Alabama,Autauga County,15,1910,871,1039,743,884,...,7,14,2,1,0,0,0,0,0,0
92,1,1,Alabama,Autauga County,16,1372,597,775,531,653,...,6,6,0,0,0,1,0,0,0,0
93,1,1,Alabama,Autauga County,17,824,327,497,297,429,...,3,4,0,0,0,0,0,0,0,0
94,1,1,Alabama,Autauga County,18,644,224,420,194,361,...,4,4,0,0,0,0,0,0,0,0
171,1,3,Alabama,Baldwin County,0,190790,93035,97755,81423,85193,...,4453,3666,220,211,189,160,53,50,46,34
172,1,3,Alabama,Baldwin County,1,11214,5735,5479,4657,4462,...,524,494,47,33,28,21,10,9,3,5
173,1,3,Alabama,Baldwin County,2,12001,6027,5974,5070,5031,...,462,404,21,23,22,14,9,4,6,6
174,1,3,Alabama,Baldwin County,3,12393,6312,6081,5268,5072,...,356,319,30,18,14,16,4,3,6,3
175,1,3,Alabama,Baldwin County,4,11641,5940,5701,4962,4687,...,343,257,9,18,11,17,6,6,5,4
176,1,3,Alabama,Baldwin County,5,10532,5299,5233,4340,4302,...,427,320,18,17,13,11,4,5,6,7
177,1,3,Alabama,Baldwin County,6,10557,5283,5274,4476,4449,...,483,349,23,16,22,4,2,5,4,0
178,1,3,Alabama,Baldwin County,7,11377,5627,5750,4880,4931,...,465,304,19,16,28,17,3,3,2,2
179,1,3,Alabama,Baldwin County,8,11268,5507,5761,4855,4976,...,355,277,10,13,11,15,1,3,3,3
180,1,3,Alabama,Baldwin County,9,12769,6303,6466,5550,5657,...,307,226,11,15,7,11,5,1,7,2
181,1,3,Alabama,Baldwin County,10,13065,6354,6711,5648,5836,...,223,183,10,13,14,11,3,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298479,56,43,Wyoming,Washakie County,8,456,233,223,222,217,...,22,27,0,0,3,1,0,0,0,0
298480,56,43,Wyoming,Washakie County,9,418,227,191,217,180,...,28,23,0,0,4,4,0,0,0,0
298481,56,43,Wyoming,Washakie County,10,567,273,294,265,282,...,40,28,0,0,3,0,0,1,0,0
298482,56,43,Wyoming,Washakie County,11,632,306,326,290,311,...,28,29,2,0,2,4,0,1,0,0
298483,56,43,Wyoming,Washakie County,12,642,339,303,324,293,...,20,18,0,1,4,3,0,0,0,0
298484,56,43,Wyoming,Washakie County,13,551,275,276,268,272,...,23,24,0,0,2,0,0,0,0,0
298485,56,43,Wyoming,Washakie County,14,485,240,245,238,239,...,6,14,0,0,1,1,0,0,0,0
298486,56,43,Wyoming,Washakie County,15,377,191,186,188,181,...,16,9,0,0,0,0,0,0,0,0
298487,56,43,Wyoming,Washakie County,16,263,107,156,106,153,...,7,8,0,0,1,0,0,0,0,0
298488,56,43,Wyoming,Washakie County,17,245,123,122,121,119,...,6,4,0,0,0,0,0,0,0,0
298489,56,43,Wyoming,Washakie County,18,211,84,127,80,123,...,5,3,0,0,0,0,0,0,0,0
298566,56,45,Wyoming,Weston County,0,7082,3728,3354,3553,3205,...,130,98,7,6,21,12,1,2,1,0
298567,56,45,Wyoming,Weston County,1,422,204,218,194,194,...,7,19,0,2,0,3,0,0,0,0
298568,56,45,Wyoming,Weston County,2,460,222,238,203,220,...,4,14,0,2,4,4,0,2,0,0
298569,56,45,Wyoming,Weston County,3,408,221,187,206,175,...,11,6,2,0,2,0,0,0,0,0
298570,56,45,Wyoming,Weston County,4,405,218,187,205,177,...,10,9,0,1,2,0,0,0,0,0
298571,56,45,Wyoming,Weston County,5,383,234,149,225,134,...,19,4,0,1,0,2,0,0,0,0
298572,56,45,Wyoming,Weston County,6,404,231,173,223,166,...,15,7,1,0,2,2,0,0,0,0
298573,56,45,Wyoming,Weston County,7,469,269,200,254,186,...,16,6,2,0,3,0,0,0,1,0
298574,56,45,Wyoming,Weston County,8,396,212,184,191,172,...,9,8,0,0,1,1,1,0,0,0
298575,56,45,Wyoming,Weston County,9,410,232,178,217,175,...,9,5,0,0,2,0,0,0,0,0
298576,56,45,Wyoming,Weston County,10,445,233,212,222,208,...,7,4,0,0,2,0,0,0,0,0
298577,56,45,Wyoming,Weston County,11,593,319,274,301,267,...,6,3,2,0,2,0,0,0,0,0
298578,56,45,Wyoming,Weston County,12,617,324,293,315,285,...,6,6,0,0,0,0,0,0,0,0
298579,56,45,Wyoming,Weston County,13,474,270,204,267,201,...,8,3,0,0,0,0,0,0,0,0
298580,56,45,Wyoming,Weston County,14,367,187,180,181,176,...,0,0,0,0,0,0,0,0,0,0
298581,56,45,Wyoming,Weston County,15,280,121,159,121,155,...,1,1,0,0,0,0,0,0,0,0
298582,56,45,Wyoming,Weston County,16,205,95,110,94,107,...,1,1,0,0,0,0,0,0,0,0
298583,56,45,Wyoming,Weston County,17,157,69,88,68,87,...,1,0,0,0,1,0,0,0,0,0
298584,56,45,Wyoming,Weston County,18,187,67,120,66,120,...,0,2,0,0,0,0,0,0,0,0

In [64]:
new_pop_data = pd.DataFrame()

In [65]:
# create a easier table
new_pop_data['State Name'] = pop_data[pop_data['AGEGRP'] == 0]['STNAME']
new_pop_data['County Name'] = pop_data[pop_data['AGEGRP'] == 0]['CTYNAME']
new_pop_data['County Fip'] = np.vectorize(lambda x,y : x * 1000 + y)(pop_data[pop_data['AGEGRP'] == 0]['STATE'], pop_data[pop_data['AGEGRP'] == 0]['COUNTY'])
new_pop_data['Total Pop'] = pop_data[pop_data['AGEGRP'] == 0]['TOT_POP']
new_pop_data['Total Male Pop'] = np.vectorize(lambda x,z : x/z)(pop_data[pop_data['AGEGRP'] == 1]['TOT_MALE'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['Total Femle Pop'] = np.vectorize(lambda x,z : x/z)(pop_data[pop_data['AGEGRP'] == 1]['TOT_FEMALE'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 0-10'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 1]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 2]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 11-20'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 3]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 4]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 21-30'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 5]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 6]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 31-40'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 7]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 8]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 41-50'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 9]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 10]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 51-60'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 11]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 12]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 61-70'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 13]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 14]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 71-80'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 15]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 16]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])
new_pop_data['% 81+'] = np.vectorize(lambda x,y,z : (x+y)/z)(pop_data[pop_data['AGEGRP'] == 17]['TOT_POP'],pop_data[pop_data['AGEGRP'] == 18]['TOT_POP'], pop_data[pop_data['AGEGRP'] == 0]['TOT_POP'])

In [66]:
new_pop_data.to_csv('population_by_county.csv')

In [53]:
education_data = pd.DataFrame()

In [48]:
raw_education_data = pd.read_csv('our_data/education.csv')

In [49]:
raw_education_data

,FIPS Code,State,Area name,"Less than a high school diploma, 2014-18","High school diploma only, 2014-18","Some college or associate's degree, 2014-18","Bachelor's degree or higher, 2014-18","Percent of adults with less than a high school diploma, 2014-18","Percent of adults with a high school diploma only, 2014-18","Percent of adults completing some college or associate's degree, 2014-18","Percent of adults with a bachelor's degree or higher, 2014-18"
0,1000,AL,Alabama,"470,043","1,020,172","987,148","822,595",14.2,30.9,29.9,24.9
1,1001,AL,Autauga County,"4,204","12,119","10,552","10,291",11.3,32.6,28.4,27.7
2,1003,AL,Baldwin County,"14,310","40,579","46,025","46,075",9.7,27.6,31.3,31.3
3,1005,AL,Barbour County,"4,901","6,486","4,566","2,220",27.0,35.7,25.1,12.2
4,1007,AL,Bibb County,"2,650","7,471","3,846","1,813",16.8,47.3,24.4,11.5
5,1009,AL,Blount County,"7,861","13,489","13,267","5,010",19.8,34.0,33.5,12.6
6,1011,AL,Bullock County,"1,760","2,817","1,582",945,24.8,39.7,22.3,13.3
7,1013,AL,Butler County,"2,141","6,091","3,421","2,235",15.4,43.9,24.6,16.1
8,1015,AL,Calhoun County,"12,620","25,653","26,643","14,219",15.9,32.4,33.7,18.0
9,1017,AL,Chambers County,"4,383","9,060","7,003","3,118",18.6,38.4,29.7,13.2
10,1019,AL,Cherokee County,"3,692","7,157","5,417","2,407",19.8,38.3,29.0,12.9
11,1021,AL,Chilton County,"5,302","13,125","7,147","4,219",17.8,44.1,24.0,14.2
12,1023,AL,Choctaw County,"1,754","3,606","2,851","1,225",18.6,38.2,30.2,13.0
13,1025,AL,Clarke County,"3,175","7,372","4,205","2,118",18.8,43.7,24.9,12.6
14,1027,AL,Clay County,"2,275","3,366","2,700",944,24.5,36.3,29.1,10.2
15,1029,AL,Cleburne County,"2,364","4,135","2,518","1,428",22.6,39.6,24.1,13.7
16,1031,AL,Coffee County,"4,833","9,723","12,181","8,175",13.8,27.9,34.9,23.4
17,1033,AL,Colbert County,"6,016","13,927","11,459","7,236",15.6,36.0,29.7,18.7
18,1035,AL,Conecuh County,"1,703","4,315","1,881",949,19.2,48.8,21.3,10.7
19,1037,AL,Coosa County,"1,675","3,178","2,424",953,20.4,38.6,29.5,11.6
20,1039,AL,Covington County,"4,530","9,368","8,588","3,952",17.1,35.4,32.5,14.9
21,1041,AL,Crenshaw County,"2,091","3,753","2,326","1,505",21.6,38.8,24.0,15.6
22,1043,AL,Cullman County,"10,405","20,382","18,559","7,866",18.2,35.6,32.4,13.7
23,1045,AL,Dale County,"4,732","10,924","12,036","5,690",14.2,32.7,36.1,17.0
24,1047,AL,Dallas County,"5,135","9,368","8,076","4,021",19.3,35.2,30.4,15.1
25,1049,AL,DeKalb County,"12,394","15,956","13,441","6,085",25.9,33.3,28.1,12.7
26,1051,AL,Elmore County,"7,594","18,304","16,197","13,664",13.6,32.8,29.0,24.5
27,1053,AL,Escambia County,"4,792","11,546","6,340","3,287",18.5,44.5,24.4,12.7
28,1055,AL,Etowah County,"11,147","23,665","24,416","12,767",15.5,32.9,33.9,17.7
29,1057,AL,Fayette County,"2,060","4,868","3,273","1,516",17.6,41.5,27.9,12.9
...,...,...,...,...,...,...,...,...,...,...,...
3173,55131,WI,Washington County,"4,939","28,658","31,889","28,989",5.2,30.3,33.8,30.7
3174,55133,WI,Waukesha County,"10,862","64,734","81,652","122,742",3.9,23.1,29.2,43.8
3175,55135,WI,Waupaca County,"3,019","15,874","11,127","7,074",8.1,42.8,30.0,19.1
3176,55137,WI,Waushara County,"2,497","7,591","5,204","2,853",13.8,41.8,28.7,15.7
3177,55139,WI,Winnebago County,"8,243","38,404","36,399","31,210",7.2,33.6,31.9,27.3
3178,55141,WI,Wood County,"3,739","19,640","17,451","11,233",7.2,37.7,33.5,21.6
3179,56000,WY,Wyoming,"27,644","111,899","145,071","104,677",7.1,28.7,37.3,26.9
3180,56001,WY,Albany County,848,"3,383","6,333","10,531",4.0,16.0,30.0,49.9
3181,56003,WY,Big Horn County,808,"2,334","3,380","1,508",10.1,29.1,42.1,18.8
3182,56005,WY,Campbell County,"2,345","10,364","11,884","5,862",7.7,34.0,39.0,19.2
3183,56007,WY,Carbon County,"1,039","3,725","3,670","2,147",9.8,35.2,34.7,20.3
3184,56009,WY,Converse County,962,"3,627","3,274","1,629",10.1,38.2,34.5,17.2
3185,56011,WY,Crook County,348,"1,486","2,145","1,148",6.8,29.0,41.8,22.4
3186,56013,WY,Fremont County,"2,336","8,267","9,739","6,236",8.8,31.1,36.6,23.5
3187,56015,WY,Goshen County,693,"2,734","3,658","2,295",7.4,29.1,39.0,24.5
3188,56017,WY,Hot Springs County,200,"1,004","1,552",829,5.6,28.0,43.3,23.1
3189,56019,WY,Johnson County,271,"1,793","2,301","1,768",4.4,29.2,37.5,28.8
3190,56021,WY,Laramie County,"4,502","16,968","25,459","18,845",6.8,25.8,38.7,28.7
3191,56023,WY,Lincoln County,777,"3,998","4,964","2,841",6.2,31.8,39.5,22.6
3192,56025,WY,Natrona County,"4,111","15,791","22,207","12,348",7.5,29.0,40.8,22.7
3193,56027,WY,Niobrara County,209,550,707,292,11.9,31.3,40.2,16.6
3194,56029,WY,Park County,"1,087","5,534","7,466","6,654",5.2,26.7,36.0,32.1
3195,56031,WY,Platte County,415,"2,333","2,181","1,369",6.6,37.0,34.6,21.7
3196,56033,WY,Sheridan County,"1,018","5,149","8,678","6,358",4.8,24.3,40.9,30.0
3197,56035,WY,Sublette County,255,"2,465","2,465","1,751",3.7,35.5,35.5,25.2
3198,56037,WY,Sweetwater County,"2,549","9,433","10,108","6,243",9.0,33.3,35.7,22.0
3199,56039,WY,Teton County,958,"2,272","4,087","9,847",5.6,13.2,23.8,57.4
3200,56041,WY,Uinta County,934,"5,176","4,810","1,995",7.2,40.1,37.2,15.4
3201,56043,WY,Washakie County,590,"1,717","2,135","1,220",10.4,30.3,37.7,21.5
3202,56045,WY,Weston County,389,"1,796","1,868",961,7.8,35.8,37.3,19.2

In [58]:
education_data['County Fip'] = raw_education_data['FIPS Code']
education_data['State Name'] = raw_education_data['State']
education_data['County Name'] = raw_education_data['Area name']
education_data['% high school only'] = raw_education_data['Percent of adults with a high school diploma only, 2014-18'].values/100
education_data['% college or higher'] = raw_education_data['Percent of adults with a bachelor\'s degree or higher, 2014-18'].values/100

In [60]:
education_data.to_csv('education_data.csv')